### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by YangAngel** [gitlabhq/gitlab-recipes#237]
Checked without error, but 500 error in browser. 
Another logs empty. What's wrong? 
CentOS 6.5 + nginx
Manual: https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md

sidekiq.log

```
2014-10-21T09:16:41Z 8590 TID-ovpxvajes INFO: Booting Sidekiq 2.17.0 with redis options {:url=>"unix:/var/run/redis/redis.sock", :namespace=>"resque:gitlab"}
2014-10-21T09:16:41Z 8590 TID-ovpxvajes INFO: Running in ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
2014-10-21T09:16:41Z 8590 TID-ovpxvajes INFO: See LICENSE and the LGPL-3.0 for licensing details.
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: Error fetching message: No such file or directory - connect(2) for /var/run/redis/redis.sock
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect_nonblock'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:178:in `connect'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:273:in `establish_connection'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:69:in `connect'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:228:in `with_socket_timeout'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:166:in `call_with_timeout'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:1037:in `block in _bpop'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `block in synchronize'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `synchronize'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:1034:in `_bpop'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:1079:in `brpop'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-namespace-1.4.1/lib/redis/namespace.rb:352:in `method_missing'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/fetch.rb:89:in `block in retrieve_work'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/connection_pool-1.2.0/lib/connection_pool.rb:55:in `with'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq.rb:67:in `redis'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/fetch.rb:89:in `retrieve_work'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/fetch.rb:34:in `block in fetch'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/util.rb:15:in `watchdog'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/fetch.rb:30:in `fetch'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2014-10-21T09:16:41Z 8590 TID-ovpxxl4dg ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
2014-10-21T09:16:43Z 8590 TID-ovpxxk9r8 ERROR: No such file or directory - connect(2) for /var/run/redis/redis.sock
2014-10-21T09:16:43Z 8590 TID-ovpxxk9r8 ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect_nonblock'
2014-10-21T09:16:58Z 8590 TID-ovpxxk9r8 ERROR: No such file or directory - connect(2) for /var/run/redis/redis.sock
2014-10-21T09:16:58Z 8590 TID-ovpxxk9r8 ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect_nonblock'
2014-10-21T09:17:13Z 8590 TID-ovpxxk9r8 ERROR: No such file or directory - connect(2) for /var/run/redis/redis.sock
2014-10-21T09:17:13Z 8590 TID-ovpxxk9r8 ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect_nonblock'
2014-10-21T09:17:28Z 8590 TID-ovpxxk9r8 ERROR: No such file or directory - connect(2) for /var/run/redis/redis.sock
2014-10-21T09:17:28Z 8590 TID-ovpxxk9r8 ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:149:in `connect_nonblock'
```

**Comment by HumanG33k** [comment]
For future people.
I think the trouble may come from redis or missing dependencies for redis in gitlab. first thing to check is the gitlab configuration file (redis part) and the redis configuration. they should be configure with the same address:port/socket file and auth stuff should be good.  I guess the issue can be close
