### ISSUE TITLE
gitlab not work , please help me thanks !!

### ISSUE THREAD

**Issue by zhonglinzhao** [gitlabhq/gitlab-recipes#276]
git pull
```
/usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:62:in `get'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:17:in `allowed?'
	from /home/git/gitlab-shell/lib/gitlab_shell.rb:59:in `validate_access'
	from /home/git/gitlab-shell/lib/gitlab_shell.rb:23:in `exec'
	from /home/git/gitlab-shell/bin/gitlab-shell:16:in `<main>'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

```
bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System:		CentOS 6.7
Current User:	root
Using RVM:	no
Ruby Version:	2.0.0p353
Gem Version:	2.0.14
Bundler Version:1.10.6
Rake Version:	10.1.0

GitLab information
Version:	6.3.1
Revision:	779b4dc
Directory:	/home/git/gitlab
DB Adapter:	mysql2
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.8.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git
```

```
bundle exec rake gitlab:check RAILS_ENV=production
Checking Environment ...

Git configured for git user? ... no
  Try fixing it:
  sudo -u git -H git config --global user.name  "GitLab"
  sudo -u git -H git config --global user.email "xxx@xxx.net"
  For more information see:
  doc/install/installation.md in section "GitLab"
  Please fix the error above and rerun the checks.
Has python2? ... yes
python2 is supported version? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ...
..
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:62:in `get'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:29:in `check'
	from /home/git/gitlab-shell/bin/check:11:in `<main>'
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /home/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... no
  Try fixing it:
  sudo -u git -H RAILS_ENV=production script/background_jobs start
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  see log/sidekiq.log for possible errors
  Please fix the error above and rerun the checks.

Checking Sidekiq ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
projects have namespace: ...
```

```
service gitlab start
Password:
Starting unicorn: runuser: cannot set groups: Operation not permitted
                                                           [FAILED]
Starting sidekiq: runuser: cannot set groups: Operation not permitted
                                                           [FAILED]
```

```
service gitlab status
unicorn is stopped
sidekiq is stopped
```

**Comment by zhonglinzhao** [comment]
Find the answer，~/.bash_profile can not have echo.
